// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adoyhjajoggbjgsxlxid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkb3loamFqb2dnYmpnc3hseGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjExMzUsImV4cCI6MjA2ODkzNzEzNX0.B2Zj1eqM-q0nOE_wo7TAlOrLsLlRospyGEjPhZ4yaes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});